/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "hzfontdemo.h"
#include "EmWinHZFont.h"
#include "ff.h"
#include "exfuns.h"
#include "malloc.h"
#include "rtc.h"

#if SYSTEM_SUPPORT_OS
#include "includes.h"					//ucos 使用	  
#endif

#include "stdlib.h"
#include "lib_str.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_TEXT_0     (GUI_ID_USER + 0x01)
#define ID_EDIT_0     (GUI_ID_USER + 0x02)
#define ID_EDIT_1     (GUI_ID_USER + 0x03)
#define ID_BUTTON_0     (GUI_ID_USER + 0x04)
#define ID_LISTVIEW_0     (GUI_ID_USER + 0x05)
#define ID_SCROLLBAR_0     (GUI_ID_USER + 0x06)
#define ID_TEXT_1     (GUI_ID_USER + 0x07)
#define ID_EDIT_2     (GUI_ID_USER + 0x08)
#define ID_EDIT_3     (GUI_ID_USER + 0x09)
#define ID_BUTTON_1     (GUI_ID_USER + 0x0A)
#define ID_BUTTON_2     (GUI_ID_USER + 0x0B)
#define ID_BUTTON_3     (GUI_ID_USER + 0x0C)


// USER START (Optionally insert additional defines)
extern WM_HWIN hDialog;

typedef enum _ELineType_ {
  LINE_IDLE,		//未处理行
	LINE_ERROR,		//错误行
	LINE_EMPTY,		//空白行或注释行
	LINE_SECTION,	//节定义行
	LINE_VALUE		//值定义行
} ELineType ;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

static FIL f_rec;
static const	char *pname_fan ="0:fan/fan_record.xls";
static char *fan_record_buf;///////
static UINT fan_record_len;
static int fan_record_line;

#define MAX_FAN_RECORD 100
#define COLUMN_MAX	4
#define LINE_LEN	40
static char **tempfan;
static  char **fan_record_list[MAX_FAN_RECORD][4];
static int cur_number;
static  char *fan_ListView1[7][4];
static  char *fan_ListView[][4]={
	{"1    ",	"2019-5-11 18:34:20", "2019-5-11 18:34:20", "10"},
	{"2    ",	"2019-5-11 18:34:20", "2019-5-11 18:34:20", "10"},
	{"3    ",	"2019-5-11 18:34:20", "2019-5-11 18:34:20", "10"},
	{"4    ",	"2019-5-11 18:34:20", "2019-5-11 18:34:20", "10"},
	{"5    ",	"2019-5-11 18:34:20", "2019-5-11 18:34:20", "10"},
	{"6    ",	"2019-5-11 18:34:20", "2019-5-11 18:34:20", "10"},
	{"7    ",	"2019-5-11 18:34:20", "2019-5-11 18:34:20", "10"},
};
static char *num[MAX_FAN_RECORD];

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Fan_Record", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "time", ID_TEXT_0, 26, 13, 113, 39, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 96, 20, 164, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 334, 17, 155, 31, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_0, 584, 17, 123, 34, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 1, 57, 760, 308, 0, 0x0, 0 },
  { SCROLLBAR_CreateIndirect, "Scrollbar", ID_SCROLLBAR_0, 761, 60, 20, 305, 8, 0x0, 0 },
  { TEXT_CreateIndirect, "page", ID_TEXT_1, 44, 377, 314, 26, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 105, 373, 50, 27, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 199, 373, 48, 27, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "previous", ID_BUTTON_1, 276, 373, 98, 28, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "next", ID_BUTTON_2, 396, 373, 100, 28, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "close", ID_BUTTON_3, 575, 372, 114, 41, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

void save_fan_record(FAN * fan)
{	
	u8 res;	
	char buf[100];
	
	res=f_open(&f_rec,(const TCHAR*)pname_fan, FA_READ | FA_WRITE); 
	if(res)			//文件创建失败
	{
		res=f_open(&f_rec,(const TCHAR*)pname_fan, FA_CREATE_ALWAYS | FA_WRITE); 
		//sprintf(buf,"序号\t开始时间\t结束时间\t运行时间\r\n");
		//res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);
		f_close(&f_rec);
		res=f_open(&f_rec,(const TCHAR*)pname_fan, FA_READ | FA_WRITE); 
	}
	
		res=f_lseek(&f_rec,f_rec.obj.objsize);
		sprintf(buf,"1\t20%02d-%02d-%02d %02d:%02d:%02d\t20%02d-%02d-%02d %02d:%02d:%02d \t%d\r",	
					fan->start_date.Year, fan->start_date.Month, fan->start_date.Date,
					fan->start_time.Hours, fan->start_time.Minutes, fan->start_time.Seconds,
					fan->end_date.Year, fan->end_date.Month, fan->end_date.Date,
					fan->end_time.Hours, fan->end_time.Minutes, fan->end_time.Seconds,
					fan->Last_run_min);
		res=f_write(&f_rec,(const void*)buf,strlen(buf),&bw);
		f_close(&f_rec);
	
}
/*
static int GetLine(char *buf, int buflen)//, char *content, char **rem1, char **rem2, char **nextline)
 { 
	char *cont1, *cont2;
	int cntblank, cntCR, cntLF;		//连续空格、换行符数量
	char isQuot1, isQuot2;			//引号
	int i,Row,Column,k;
	char *p;
 
	for (i = 0, p = buf; i < buflen; i ++, p ++) 
	{ 
 		switch (*p) {
			case '\r':
				//cntCR ++;
			fan_record_list[Row][COLUMN_MAX-1] = p-k;
			k=0;
			Row++;
				break;
			case '\n':
				cntLF ++;
				break;
			//case ''':
			case '\t':
				fan_record_list[Row][Column] = p-k;
				k=0;
				Column++;
				if(Column >= COLUMN_MAX-1)
					Column = 0;
				break;
		default: 
			k++;
			break;
 		}
 	}
			
	return Row; 
}*/

static void update_fan_List(WM_MESSAGE * pMsg, int number){
	int i,j;
	WM_HWIN hItem;
	
	for(i=0; i<7;i++){
		if((i+number) > (fan_record_line-1)){
			for(j = 0; j<5; j++)
				sprintf((char*)fan_ListView[i][j],"");
		}else{
		/**/
			fan_ListView[i][0] = *fan_record_list[i+number][0];
			fan_ListView[i][1] = *fan_record_list[i+number][1];
			fan_ListView[i][2] = *fan_record_list[i+number][2];
			fan_ListView[i][3] = *fan_record_list[i+number][3];

		}
	}
	hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
	for (i = 0; i < 7; i++)
		for (j = 0; j < GUI_COUNTOF(fan_ListView[i]); j++) {
				LISTVIEW_SetItemText(hItem, j, i, fan_ListView[i][j]);
		}
}

static int read_fan_record(){
	#if SYSTEM_SUPPORT_OS
		CPU_SR_ALLOC();
	#endif
	u8 res;	
	char *p_pre,*p_cur;
	char *p;
	int number,len,i,j;
	char *buf[100];
	
	res=f_open(&f_rec,(const TCHAR*)pname_fan, FA_READ | FA_WRITE); 
	if(res != FR_OK)		return	1;
	
  fan_record_buf=(char *)mymalloc(SRAMIN,f_rec.obj.objsize);		//开辟fan_record_buf内存区域
	if( fan_record_buf==NULL)		return	2;	
	
	#if SYSTEM_SUPPORT_OS
		OS_CRITICAL_ENTER();		//临界区
	#endif
	res = f_read(&f_rec, fan_record_buf,f_rec.obj.objsize,&fan_record_len );	
	if(res != FR_OK)	return	3;
	#if SYSTEM_SUPPORT_OS
		OS_CRITICAL_EXIT();	//退出临界区
	#endif	
	f_close(&f_rec);	
//return 0;
	p_cur = p_pre = fan_record_buf; 
	for(i = 0,len=0,fan_record_line=0; i<fan_record_len;i++){
		p_cur = Str_Char(fan_record_buf+len, '\r');
		if(p_cur == NULL)break;
		fan_record_line++;
		len += p_cur+1-p_pre;
		p_pre = p_cur+1;
	}
	for(i = 0; i<fan_record_line;i++){
		num[i]=(char *)mymalloc(SRAMIN,3);		//开辟num内存区域
		if( num[i]==NULL)		{
			for( j=0;j<i;j++)
				myfree(SRAMIN,num[i]);
			return	4;
		}
		else sprintf(num[i], "%d",i);
	}
	
	for(i = 0; i<fan_record_line;i++)
		for(j = 0;j<4;j++){
				fan_record_list[i][j]=(char **)mymalloc(SRAMIN,sizeof(char *));		//开辟fan_record_list,40字节的内存区域
				if(fan_record_list[i][j]==NULL){
					for(int m=0;m<i;m++)
						for(int n=0;n<j;n++){
							myfree(SRAMIN,fan_record_list[i][j]);		//释放内存	
						}
					myfree(SRAMIN,fan_record_buf);		//释放内存
					return	4;
				}else{
					mymemset(fan_record_list[i][j],0,sizeof(char *));        //先清零
				}
		}
	p_cur = p_pre = fan_record_buf;	
	for(number = 0,len=0; number < fan_record_line; number++){	
		p_cur = Str_Char(fan_record_buf+len, '\t');//'\t'
		*p_cur = 0x00;
		//sprintf(*fan_record_list[number][0], "%d ",number);
		sprintf(buf[0], "%d ",number);
		
		//sprintf(buf, "%d",number);		
		*fan_record_list[number][0] = num[number];
		
		//*fan_record_list[number][0] = p_pre;
		len += p_cur+1-p_pre;
		p_pre = p_cur+1;
		
		p_cur = Str_Char(fan_record_buf+len, '\t');
		*p_cur = 0x00;
		*fan_record_list[number][1] = p_pre;
		len += p_cur+1-p_pre;
		p_pre = p_cur+1;
		
		p_cur = Str_Char(fan_record_buf+len, '\t');
		*p_cur = 0x00;
		*fan_record_list[number][2] = p_pre;
		len += p_cur+1-p_pre;
		p_pre = p_cur+1;
		
		p_cur = Str_Char(fan_record_buf+len, '\r');//'\r'
		*p_cur = 0x00;
		
		//sprintf(*fan_record_list[number][3],"%d",fan_record_line);
		*fan_record_list[number][3] = p_pre;
		/*
		char line[50];
		sprintf(line, "%d",fan_record_line);		
		*fan_record_list[number][3]= &line[0];
		*/
		len += p_cur+1-p_pre;
		p_pre = p_cur+1;
		/**/
	}
	return 0;
}

static void init_fan_List(WM_MESSAGE * pMsg){
	WM_HWIN hItem;
	WM_HWIN hHeader;
	int i,j;
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
	hHeader = LISTVIEW_GetHeader(hItem);
	LISTVIEW_SetHeaderHeight(hItem, 100);
	HEADER_SetFont(hHeader,&GUI_FontHZ24);
	LISTVIEW_AddColumn(hItem, 100, "序号", GUI_TA_HCENTER | GUI_TA_VCENTER);
	LISTVIEW_AddColumn(hItem, 200, "开始时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
	LISTVIEW_AddColumn(hItem, 200, "停止时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
	LISTVIEW_AddColumn(hItem, 100, "运行分钟", GUI_TA_HCENTER | GUI_TA_VCENTER);
	LISTVIEW_SetGridVis(hItem, 1);
	LISTVIEW_SetAutoScrollH(hItem, 1);
	LISTVIEW_SetAutoScrollV(hItem, 1);
	LISTVIEW_SetRowHeight(hItem, 30);
	LISTVIEW_SetFont(hItem,&GUI_FontHZ16);
	LISTVIEW_SetBkColor(hItem,LISTVIEW_CI_UNSEL,GUI_ORANGE);
	
	if(read_fan_record()!= FR_OK) return;
	for(i=0;i<GUI_COUNTOF(fan_ListView);i++)
	{
		LISTVIEW_AddRow(hItem,fan_ListView[i]);
	}
	//cur_number= 0;
	update_fan_List(pMsg,cur_number);
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	hItem = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Fan_Record'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_32_ASCII);
    //
    // Initialization of 'time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'OK'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'Listview'
    //
		init_fan_List(pMsg);
		/*
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    LISTVIEW_AddColumn(hItem, 60, "Col 0", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 350, "Col 1", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 350, "Col 2", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_SetFont(hItem, GUI_FONT_20_ASCII);
		*/
    //
    // Initialization of 'page'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'previous'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'next'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'close'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'OK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SCROLLBAR_0: // Notifications sent by 'Scrollbar'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'previous'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				if(cur_number >=7 ){
					cur_number = cur_number - 7;
					update_fan_List(pMsg,cur_number);
				}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'next'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			if(cur_number < (fan_record_line-7) ){
					cur_number =cur_number +7;
					update_fan_List(pMsg,cur_number);
			}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'close'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)	
				for(int i = 0; i<fan_record_line;i++)
					for(int j = 0;j<4;j++){
					myfree(SRAMIN,fan_record_list[i][j]);		//释放fan_record_list,40字节的内存区域
				}							
				myfree(SRAMIN,fan_record_buf);		//释放fan_record_buf内存		
				for(int i = 0; i<fan_record_line;i++){
					myfree(SRAMIN,num[i]);
				}					
				GUI_EndDialog(hItem, 0 );
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFan_Record
*/
WM_HWIN CreateFan_Record(void);
WM_HWIN CreateFan_Record(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
