/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "EmWinHZFont.h"
#include "sys_set.h"
//#include "ini.h"
#include "files.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*
#define ID_FRAMEWIN_0  (GUI_ID_USER + 0x00)
#define ID_TEXT_0  (GUI_ID_USER + 0x01)
#define ID_TEXT_1  (GUI_ID_USER + 0x02)
#define ID_TEXT_2  (GUI_ID_USER + 0x03)
#define ID_TEXT_3  (GUI_ID_USER + 0x04)
#define ID_CHECKBOX_0  (GUI_ID_USER + 0x08)
#define ID_CHECKBOX_1  (GUI_ID_USER + 0x07)
#define ID_CHECKBOX_2  (GUI_ID_USER + 0x06)
#define ID_CHECKBOX_3  (GUI_ID_USER + 0x05)
#define ID_TEXT_4  (GUI_ID_USER + 0x09)
#define ID_TEXT_5  (GUI_ID_USER + 0x0A)
#define ID_TEXT_6  (GUI_ID_USER + 0x0B)
#define ID_TEXT_7  (GUI_ID_USER + 0x0C)
#define ID_DROPDOWN_0  (GUI_ID_USER + 0x0D)
#define ID_DROPDOWN_1  (GUI_ID_USER + 0x0E)
#define ID_DROPDOWN_2  (GUI_ID_USER + 0x0F)
#define ID_DROPDOWN_3  (GUI_ID_USER + 0x10)
#define ID_DROPDOWN_4  (GUI_ID_USER + 0x11)
#define ID_DROPDOWN_5  (GUI_ID_USER + 0x12)
#define ID_DROPDOWN_6  (GUI_ID_USER + 0x13)
#define ID_DROPDOWN_7  (GUI_ID_USER + 0x14)
#define ID_DROPDOWN_8  (GUI_ID_USER + 0x15)
#define ID_DROPDOWN_9  (GUI_ID_USER + 0x16)
#define ID_DROPDOWN_10  (GUI_ID_USER + 0x17)
#define ID_DROPDOWN_11  (GUI_ID_USER + 0x18)
#define ID_DROPDOWN_12  (GUI_ID_USER + 0x19)
#define ID_DROPDOWN_13  (GUI_ID_USER + 0x1A)
#define ID_DROPDOWN_14  (GUI_ID_USER + 0x1B)
#define ID_DROPDOWN_15  (GUI_ID_USER + 0x1C)
#define ID_DROPDOWN_16  (GUI_ID_USER + 0x1D)
#define ID_DROPDOWN_17  (GUI_ID_USER + 0x1E)
#define ID_DROPDOWN_18  (GUI_ID_USER + 0x1F)
#define ID_DROPDOWN_19  (GUI_ID_USER + 0x20)
#define ID_DROPDOWN_20  (GUI_ID_USER + 0x21)
#define ID_DROPDOWN_21  (GUI_ID_USER + 0x22)
#define ID_DROPDOWN_22  (GUI_ID_USER + 0x23)
#define ID_DROPDOWN_23  (GUI_ID_USER + 0x24)
#define ID_DROPDOWN_24  (GUI_ID_USER + 0x25)
#define ID_DROPDOWN_25  (GUI_ID_USER + 0x26)
#define ID_DROPDOWN_26  (GUI_ID_USER + 0x27)
#define ID_DROPDOWN_27  (GUI_ID_USER + 0x28)
#define ID_DROPDOWN_28  (GUI_ID_USER + 0x29)
#define ID_DROPDOWN_29  (GUI_ID_USER + 0x2A)
#define ID_DROPDOWN_30  (GUI_ID_USER + 0x2B)
#define ID_DROPDOWN_31  (GUI_ID_USER + 0x2C)
#define ID_DROPDOWN_32  (GUI_ID_USER + 0x2D)
#define ID_DROPDOWN_33  (GUI_ID_USER + 0x2E)
#define ID_DROPDOWN_34  (GUI_ID_USER + 0x2F)
#define ID_DROPDOWN_35  (GUI_ID_USER + 0x30)
#define ID_DROPDOWN_36  (GUI_ID_USER + 0x31)
#define ID_DROPDOWN_37  (GUI_ID_USER + 0x32)
#define ID_DROPDOWN_38  (GUI_ID_USER + 0x33)
#define ID_DROPDOWN_39  (GUI_ID_USER + 0x34)
#define ID_DROPDOWN_40  (GUI_ID_USER + 0x35)
#define ID_DROPDOWN_41  (GUI_ID_USER + 0x36)
#define ID_DROPDOWN_42  (GUI_ID_USER + 0x37)
#define ID_TEXT_8  (GUI_ID_USER + 0x38)
#define ID_TEXT_9  (GUI_ID_USER + 0x39)
#define ID_TEXT_10  (GUI_ID_USER + 0x3A)
#define ID_TEXT_11  (GUI_ID_USER + 0x3B)
#define ID_TEXT_12  (GUI_ID_USER + 0x3C)
#define ID_TEXT_13  (GUI_ID_USER + 0x3D)
#define ID_TEXT_14  (GUI_ID_USER + 0x3E)
#define ID_TEXT_15  (GUI_ID_USER + 0x3F)
#define ID_TEXT_16  (GUI_ID_USER + 0x40)
#define ID_TEXT_17  (GUI_ID_USER + 0x41)
#define ID_CHECKBOX_4  (GUI_ID_USER + 0x42)
#define ID_TEXT_18  (GUI_ID_USER + 0x43)
#define ID_TEXT_19  (GUI_ID_USER + 0x44)
#define ID_CHECKBOX_5  (GUI_ID_USER + 0x45)
#define ID_BUTTON_0  (GUI_ID_USER + 0x46)
#define ID_BUTTON_1  (GUI_ID_USER + 0x47)
#define ID_TEXT_20  (GUI_ID_USER + 0x48)


// USER START (Optionally insert additional defines)
*/
#define	ID_FRAMEWIN_0	(GUI_ID_USER	+	0x00)
#define	ID_DROPDOWN_0	(GUI_ID_USER	+	0x01)
#define	ID_DROPDOWN_1	(GUI_ID_USER	+	0x02)
#define	ID_DROPDOWN_2	(GUI_ID_USER	+	0x03)
#define	ID_DROPDOWN_3	(GUI_ID_USER	+	0x04)
#define	ID_DROPDOWN_4	(GUI_ID_USER	+	0x05)
#define	ID_DROPDOWN_5	(GUI_ID_USER	+	0x06)
#define	ID_DROPDOWN_6	(GUI_ID_USER	+	0x07)
#define	ID_DROPDOWN_7	(GUI_ID_USER	+	0x08)
#define	ID_DROPDOWN_8	(GUI_ID_USER	+	0x09)
#define	ID_DROPDOWN_9	(GUI_ID_USER	+	0x0A)
#define	ID_DROPDOWN_10	(GUI_ID_USER	+	0x0B)
#define	ID_DROPDOWN_11	(GUI_ID_USER	+	0x0C)
#define	ID_DROPDOWN_12	(GUI_ID_USER	+	0x0D)
#define	ID_DROPDOWN_13	(GUI_ID_USER	+	0x0E)
#define	ID_DROPDOWN_14	(GUI_ID_USER	+	0x0F)
#define	ID_DROPDOWN_15	(GUI_ID_USER	+	0x10)
#define	ID_DROPDOWN_16	(GUI_ID_USER	+	0x11)
#define	ID_DROPDOWN_17	(GUI_ID_USER	+	0x12)
#define	ID_DROPDOWN_18	(GUI_ID_USER	+	0x13)
#define	ID_DROPDOWN_19	(GUI_ID_USER	+	0x14)
#define	ID_DROPDOWN_20	(GUI_ID_USER	+	0x15)
#define	ID_DROPDOWN_21	(GUI_ID_USER	+	0x16)
#define	ID_DROPDOWN_22	(GUI_ID_USER	+	0x17)
#define	ID_DROPDOWN_23	(GUI_ID_USER	+	0x18)
#define	ID_DROPDOWN_24	(GUI_ID_USER	+	0x19)
#define	ID_DROPDOWN_25	(GUI_ID_USER	+	0x1A)
#define	ID_DROPDOWN_26	(GUI_ID_USER	+	0x1B)
#define	ID_DROPDOWN_27	(GUI_ID_USER	+	0x1C)
#define	ID_DROPDOWN_28	(GUI_ID_USER	+	0x1D)
#define	ID_DROPDOWN_29	(GUI_ID_USER	+	0x1E)
#define	ID_DROPDOWN_30	(GUI_ID_USER	+	0x1F)
#define	ID_DROPDOWN_31	(GUI_ID_USER	+	0x20)
#define	ID_DROPDOWN_32	(GUI_ID_USER	+	0x21)
#define	ID_DROPDOWN_33	(GUI_ID_USER	+	0x22)
#define	ID_DROPDOWN_34	(GUI_ID_USER	+	0x23)
#define	ID_DROPDOWN_35	(GUI_ID_USER	+	0x24)
#define	ID_DROPDOWN_36	(GUI_ID_USER	+	0x25)
#define	ID_DROPDOWN_37	(GUI_ID_USER	+	0x26)
#define	ID_DROPDOWN_38	(GUI_ID_USER	+	0x27)
#define	ID_DROPDOWN_39	(GUI_ID_USER	+	0x28)
#define	ID_DROPDOWN_40	(GUI_ID_USER	+	0x29)
#define	ID_DROPDOWN_41	(GUI_ID_USER	+	0x2A)
#define	ID_DROPDOWN_42	(GUI_ID_USER	+	0x2B)
#define	ID_CHECKBOX_0	(GUI_ID_USER	+	0x2C)
#define	ID_CHECKBOX_1	(GUI_ID_USER	+	0x2D)
#define	ID_CHECKBOX_2	(GUI_ID_USER	+	0x2E)
#define	ID_CHECKBOX_3	(GUI_ID_USER	+	0x2F)
#define	ID_CHECKBOX_4	(GUI_ID_USER	+	0x30)
#define	ID_CHECKBOX_5	(GUI_ID_USER	+	0x31)
#define	ID_BUTTON_0	(GUI_ID_USER	+	0x32)
#define	ID_BUTTON_1	(GUI_ID_USER	+	0x33)
#define	ID_TEXT_0	(GUI_ID_USER	+	0x34)
#define	ID_TEXT_1	(GUI_ID_USER	+	0x35)
#define	ID_TEXT_2	(GUI_ID_USER	+	0x36)
#define	ID_TEXT_3	(GUI_ID_USER	+	0x37)
#define	ID_TEXT_4	(GUI_ID_USER	+	0x38)
#define	ID_TEXT_5	(GUI_ID_USER	+	0x39)
#define	ID_TEXT_6	(GUI_ID_USER	+	0x3A)
#define	ID_TEXT_7	(GUI_ID_USER	+	0x3B)
#define	ID_TEXT_8	(GUI_ID_USER	+	0x3C)
#define	ID_TEXT_9	(GUI_ID_USER	+	0x3D)
#define	ID_TEXT_10	(GUI_ID_USER	+	0x3E)
#define	ID_TEXT_11	(GUI_ID_USER	+	0x3F)
#define	ID_TEXT_12	(GUI_ID_USER	+	0x40)
#define	ID_TEXT_13	(GUI_ID_USER	+	0x41)
#define	ID_TEXT_14	(GUI_ID_USER	+	0x42)
#define	ID_TEXT_15	(GUI_ID_USER	+	0x43)
#define	ID_TEXT_16	(GUI_ID_USER	+	0x44)
#define	ID_TEXT_17	(GUI_ID_USER	+	0x45)
#define	ID_TEXT_18	(GUI_ID_USER	+	0x46)
#define	ID_TEXT_19	(GUI_ID_USER	+	0x47)
#define	ID_TEXT_20	(GUI_ID_USER	+	0x48)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static SYS_SET sys_set_data;
WM_HWIN	hItem_sys_dialog;
extern char IPADDR[];
extern int PORT;
extern double double_test;

LOAD_FILE file_sys;
const char *filename_sys = "0:SYS_SET/sys.ini";
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Sys_Set", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "humidity", ID_TEXT_0, 95, 110, 150, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "temperature", ID_TEXT_1, 95, 80, 150, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CO2", ID_TEXT_2, 95, 50, 150, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "O2", ID_TEXT_3, 95, 20, 125, 25, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "fan_gang4", ID_CHECKBOX_0, 380, 112, 103, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "fan_gang3", ID_CHECKBOX_1, 380, 82, 106, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "fan_gang2", ID_CHECKBOX_2, 380, 52, 111, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "fan_gang1", ID_CHECKBOX_3, 380, 22, 110, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "alarm_sounds", ID_CHECKBOX_4, 299, 317, 114, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "voice", ID_CHECKBOX_5, 212, 352, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_gang_value4", ID_TEXT_4, 495, 112, 100, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_gang_value3", ID_TEXT_5, 495, 82, 100, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_gang_value2", ID_TEXT_6, 495, 52, 100, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_gang_value1", ID_TEXT_7, 494, 22, 100, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "fan_gang_value1", ID_DROPDOWN_0, 600, 20, 80, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "fan_gang_value2", ID_DROPDOWN_1, 600, 50, 80, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "fan_gang_value3", ID_DROPDOWN_2, 600, 80, 80, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "fan_gang_value4", ID_DROPDOWN_3, 600, 110, 80, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "o2_alarm_value", ID_DROPDOWN_4, 230, 20, 80, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "co2_alarm_value", ID_DROPDOWN_5, 230, 50, 80, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "temperature_alarm_value", ID_DROPDOWN_6, 230, 80, 80, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "humidity_alarm_value", ID_DROPDOWN_7, 230, 110, 80, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing1_hour_s", ID_DROPDOWN_8, 20, 170, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing2_hour_s", ID_DROPDOWN_9, 20, 200, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing3_hour_s", ID_DROPDOWN_10, 20, 230, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing4_hour_s", ID_DROPDOWN_11, 20, 260, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing5_hour_s", ID_DROPDOWN_12, 415, 170, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing6_hour_s", ID_DROPDOWN_13, 415, 200, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing7_hour_s", ID_DROPDOWN_14, 415, 230, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing8_hour_s", ID_DROPDOWN_15, 415, 260, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing1_hour_end", ID_DROPDOWN_16, 200, 170, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing2_hour_end", ID_DROPDOWN_17, 200, 200, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing3_hour_end", ID_DROPDOWN_18, 200, 230, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing4_hour_end", ID_DROPDOWN_19, 200, 260, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing5_hour_end", ID_DROPDOWN_20, 595, 170, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing6_hour_end", ID_DROPDOWN_21, 595, 200, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing7_hour_end", ID_DROPDOWN_22, 595, 230, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing8_hour_end", ID_DROPDOWN_23, 595, 260, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing1_min_s", ID_DROPDOWN_24, 105, 170, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing2_min_s", ID_DROPDOWN_25, 105, 200, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing3_min_s", ID_DROPDOWN_26, 105, 230, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing4_min_s", ID_DROPDOWN_27, 105, 260, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing5_min_s", ID_DROPDOWN_28, 500, 170, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing6_min_s", ID_DROPDOWN_29, 500, 200, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing7_min_s", ID_DROPDOWN_30, 500, 230, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing8_min_s", ID_DROPDOWN_31, 500, 260, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing1_min_end", ID_DROPDOWN_32, 285, 170, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing2_min_end", ID_DROPDOWN_33, 285, 200, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing3_min_end", ID_DROPDOWN_34, 285, 230, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing4_min_end", ID_DROPDOWN_35, 285, 260, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing5_min_end", ID_DROPDOWN_36, 680, 170, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing6_min_end", ID_DROPDOWN_37, 680, 200, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing7_min_end", ID_DROPDOWN_38, 680, 230, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing8_min_end", ID_DROPDOWN_39, 680, 260, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "fan_run_time", ID_DROPDOWN_40, 125, 314, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, " sample_interval", ID_DROPDOWN_41, 618, 314, 55, 25, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "voice", ID_DROPDOWN_42, 88, 361, 55, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_timing_times", ID_TEXT_8, 8, 148, 257, 21, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_9, 480, 352, 257, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_10, 461, 354, 278, 23, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_11, 452, 354, 285, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_12, 454, 359, 272, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_13, 461, 358, 271, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_14, 463, 354, 262, 27, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_15, 454, 357, 300, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_16, 452, 362, 300, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_run_time", ID_TEXT_17, 16, 315, 107, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, " sample interval_time", ID_TEXT_18, 577, 341, 170, 28, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "volume", ID_TEXT_19, 26, 363, 60, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "save", ID_BUTTON_0, 277, 384, 94, 33, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "close", ID_BUTTON_1, 437, 384, 86, 31, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "print", ID_TEXT_20, 536, 393, 167, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

#include "ff.h"
#include "exfuns.h"
#include "malloc.h"

static FIL* f_rec=0;			//文件
//char *gFilename;
//char *gBuffer;
//int gBuflen;
//FIL *file_sys;


static void read_sys_set_file(){

}
/*
static void write_once_record(){
	u8 *buf=0;
	u8	res;
	int	i;
	buf=mymalloc(SRAMIN,50);						//申请30个字节内存,类似"0:RECORDER/REC00001.wav"
	buf[0]=0;
	for(i=0; i <4; i++){
		sprintf((char*)buf,"风机联动值%d\t%d\t开/关\t%d\r\n",
									i+1, sys_set_data.fan_gang[i].Value, sys_set_data.fan_gang[i].enable);
		res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);
	}
	for(i=0;i<8;i++){
		sprintf((char*)buf,"定时时间%d\t%d\t:\t%d\t--\t%d\t:\t%d\r\n",
									i+1, sys_set_data.timing[i].start_hour,sys_set_data.timing[i].start_min,
											sys_set_data.timing[i].end_hour,sys_set_data.timing[i].end_min);
		res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);
	}
	sprintf((char*)buf,"氧    气报警值\t%f\r\n",sys_set_data.alarm.O2);
	res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);
	sprintf((char*)buf,"二氧化碳报警值\t%f\r\n",sys_set_data.alarm.CO2);
	res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);
	sprintf((char*)buf,"温    度报警值\t%f\r\n",sys_set_data.alarm.Temperature);
	res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);
	sprintf((char*)buf,"湿    度报警值\t%f\r\n",sys_set_data.alarm.Humidity);
	res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);	
	sprintf((char*)buf,"风机运行时间\t%d\r\n",sys_set_data.fan_run_time);
	res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);
	sprintf((char*)buf,"报警器报警开关\t%d\r\n",sys_set_data.alarm.enable);
	res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);
	sprintf((char*)buf,"采样间隔\t%d\r\n",sys_set_data.sample_interval);
	res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);	
	sprintf((char*)buf,"语音音量\t%d\t开关\t%d\r\n",
										sys_set_data.voice.value,sys_set_data.voice.enable);
	res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);
	myfree(SRAMIN,buf);		//释放内存

}
static void write_sys_set_file(){
	DIR recdir;	 			//目录
	u8 *pname=0,*buf=0;
	u8 res;
	char pos[20]="";
	while(f_opendir(&recdir,"0:/SYS_SET"))//打开录音文件夹
 	{
		f_mkdir("0:/SYS_SET");				//创建该目录   
	}
  f_rec=(FIL *)mymalloc(SRAMIN,sizeof(FIL));		//开辟FIL字节的内存区域 
	pname=mymalloc(SRAMIN,30);						//申请30个字节内存,类似"0:RECORDER/REC00001.wav"
	buf=mymalloc(SRAMIN,30);	
	pname[0]=0;					//pname没有任何文件名
	buf[0]=0;
	sprintf((char*)pname,"0:SYS_SET/sys_set.xls");
	res=f_open(f_rec,(const TCHAR*)pname, FA_READ | FA_WRITE); 
	if(res)			//文件创建失败
	{
		res=f_open(f_rec,(const TCHAR*)pname, FA_CREATE_ALWAYS | FA_WRITE); 
		f_close(f_rec);
	}else	{	
		//sprintf((char*)buf,"fan_gang1=%d",sys_set_data.fan_gang[1].Value);
		//res=f_write(f_rec,(const void*)buf,strlen(buf),&bw);
		write_once_record();
		f_close(f_rec);
	}
	myfree(SRAMIN,f_rec);		//释放内存
	myfree(SRAMIN,pname);		//释放内存
	myfree(SRAMIN,buf);		//释放内存
}
*/
static void	init_DROPDOWN(WM_MESSAGE * pMsg)
{
	WM_HWIN	hItem;
	char	buf[2];
	U16 i,n;
	
	//风机联动值0-100
	for(n =0;n <4;n++){
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0+n);
			DROPDOWN_SetAutoScroll(hItem,1);	//启用自动使用滚动条
		for(i = 0;i<100;i++){
			sprintf(buf,"%d",i);
			DROPDOWN_AddString(hItem, buf);
		}
	}
//报警值0-100
	for(n =0;n <4;n++){
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_4+n);
			DROPDOWN_SetAutoScroll(hItem,1);	//启用自动使用滚动条
		for(i = 0;i<100;i++){
			sprintf(buf,"%d",i);
			DROPDOWN_AddString(hItem, buf);
		}
	}
	//小时0-23
	for(n =0;n <16;n++){
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_8+n);
			DROPDOWN_SetAutoScroll(hItem,1);	//启用自动使用滚动条
		for(i = 0;i<24;i++){
			sprintf(buf,"%d",i);
			DROPDOWN_AddString(hItem, buf);
		}
	}//分钟0-59
	for(n =0;n<16; n++){
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_24+n);
			DROPDOWN_SetAutoScroll(hItem,1);	//启用自动使用滚动条
		for(i = 0;i<60;i++){
			sprintf(buf,"%d",i);
			DROPDOWN_AddString(hItem, buf);
		}
	}
	//风机运行时间默认15分钟
	hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_40);
	DROPDOWN_SetAutoScroll(hItem,1);	//启用自动使用滚动条
	for(i = 0;i<100;i++){
			sprintf(buf,"%d",i);
			DROPDOWN_AddString(hItem, buf);
	}
	//变送器查询间隔
	hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_41);//默认5分钟
	DROPDOWN_SetAutoScroll(hItem,1);	//启用自动使用滚动条
	for(i = 0;i<30;i++){
			sprintf(buf,"%d",i);
			DROPDOWN_AddString(hItem, buf);
	}
	//语音音量大小
	hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_42);//0
	DROPDOWN_SetAutoScroll(hItem,1);	//启用自动使用滚动条
	for(i = 0;i<4;i++){
			sprintf(buf,"%d",i);
			DROPDOWN_AddString(hItem, buf);
	}
	
}

static void read_sys_ini(LOAD_FILE *file ){	
	int i,n;
	char buf[50];
 	FileLoad(file);
	sys_set_data.alarm.O2=GetDouble(file, "ALARM", "O2",  1);
	sys_set_data.alarm.CO2=GetDouble(file, "ALARM", "CO2",  2);
	sys_set_data.alarm.Temperature=GetDouble(file, "ALARM", "Temperature",  3);
	sys_set_data.alarm.Humidity=GetDouble(file, "ALARM", "Humidity",  4);
	sys_set_data.alarm.enable = GetInt(file, "ALARM", "enable",  1);
		
	for(i = 0; i<4; i++){
		sprintf(buf,"fan_gang%d_value",i+1);
		sys_set_data.fan_gang[i].Value=GetDouble(file, "FAN_GANG", buf, 1);
		sprintf(buf,"fan_gang%d_enable",i+1);
		sys_set_data.fan_gang[i].enable=GetInt(file, "FAN_GANG", buf, 1);
	}
	for(i = 0; i<8; i++){
		sprintf(buf,"time%d_start_hour",i+1);
		sys_set_data.timing[i].start_hour=GetInt(file, "TIMING_TIME", buf, 1);
		sprintf(buf,"time%d_start_min",i+1);
		sys_set_data.timing[i].start_min=GetInt(file, "TIMING_TIME", buf, 2);
		sprintf(buf,"time%d_end_hour",i+1);
		sys_set_data.timing[i].end_hour=GetInt(file, "TIMING_TIME", buf, 3);
		sprintf(buf,"time%d_end_min",i+1);
		sys_set_data.timing[i].end_min=GetInt(file, "TIMING_TIME", buf, 4);
	}
	sys_set_data.voice.value = GetInt(file, "VOICE","value",1);
	sys_set_data.voice.enable = GetInt(file, "VOICE","enable",1);
	sys_set_data.fan_run_time = GetInt(file, "OTHER","fan_run_time",1);	
	sys_set_data.sample_interval = GetInt(file, "OTHER","sample_interval",1);
	
	FileFree(file);
}
static void save_sys_ini(LOAD_FILE  *file){	
	int i,n;
	char buf[50];
	
 	FileLoad(file);
	SetInt(file,"ALARM", "O2", sys_set_data.alarm.O2, 10);		
	SetInt(file, "ALARM", "CO2", sys_set_data.alarm.CO2, 10);
	SetInt(file, "ALARM", "Temperature", sys_set_data.alarm.Temperature, 10);
	SetInt(file, "ALARM", "Humidity", sys_set_data.alarm.Humidity , 10);
	SetInt(file, "ALARM", "enable", sys_set_data.alarm.enable,10);
	
	for(i = 0; i<4; i++){
		sprintf(buf,"fan_gang%d_value",i+1);
		SetInt(file, "FAN_GANG", buf, sys_set_data.fan_gang[i].Value, 10);
		sprintf(buf,"fan_gang%d_enable",i+1);
		SetInt(file, "FAN_GANG", buf, sys_set_data.fan_gang[i].enable, 10);
	}
	for(i = 0; i<8; i++){
		sprintf(buf,"time%d_start_hour",i+1);
		SetInt(file, "TIMING_TIME", buf,sys_set_data.timing[i].start_hour, 10);
		sprintf(buf,"time%d_start_min",i+1);
		SetInt(file, "TIMING_TIME", buf, sys_set_data.timing[i].start_min,10);
		sprintf(buf,"time%d_end_hour",i+1);
		SetInt(file, "TIMING_TIME", buf,sys_set_data.timing[i].end_hour, 10);
		sprintf(buf,"time%d_end_min",i+1);
		SetInt(file, "TIMING_TIME", buf, sys_set_data.timing[i].end_min,10);
	}
	SetInt(file, "VOICE", "value", sys_set_data.voice.value,10);
	SetInt(file, "VOICE", "enable",sys_set_data.voice.enable , 10);
	SetInt(file, "OTHER", "fan_run_time",sys_set_data.fan_run_time, 10);	
	SetInt(file, "OTHER", "sample_interval", sys_set_data.sample_interval , 10);
	/**/
	FileFree(file);
}
static void init(WM_MESSAGE * pMsg){
	WM_HWIN hItem;
  int     NCode;
  int     Id;
	int	m,n;
	//初始化FRAMEWIN
	hItem_sys_dialog=hItem = pMsg->hWin;
	//FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//FRAMEWIN_SetTitleHeight(hItem, 10);
	FRAMEWIN_SetFont(hItem,&GUI_FontHZ32);
	//FRAMEWIN_SetTextColor(hItem, GUI_RED);
	FRAMEWIN_SetText(hItem, "系统设置");
	init_DROPDOWN(pMsg);
	
	
	file_sys.name =filename_sys;	
	read_sys_ini(&file_sys);
	
    // Initialization of 'ID_CHECKBOX_?'	
		for(n =0;n<6; n++){
			hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0+n);
			CHECKBOX_SetFont(hItem,&GUI_FontHZ16);
			if(n<4){
				CHECKBOX_SetText(hItem, "风机联动");
				CHECKBOX_SetState(hItem, sys_set_data.fan_gang[n].enable);
			}else if(n < 5){
				CHECKBOX_SetText(hItem, "报警器报警");
				CHECKBOX_SetState(hItem, sys_set_data.alarm.enable);
			}else{
				CHECKBOX_SetText(hItem, "语音");			
				CHECKBOX_SetState(hItem, sys_set_data.voice.enable);
			}
		}
		
		for(n =0; n<4; n++){
			hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0+n);
			DROPDOWN_SetSel(hItem, sys_set_data.fan_gang[n].Value);
		}
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_4);
		DROPDOWN_SetSel(hItem, sys_set_data.alarm.O2);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_5);
		DROPDOWN_SetSel(hItem, sys_set_data.alarm.CO2);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_6);
		DROPDOWN_SetSel(hItem, sys_set_data.alarm.Temperature);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_7);
		DROPDOWN_SetSel(hItem, sys_set_data.alarm.Humidity);
		
		//定时设置
		for(n =0;n<8; n++){
			hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_8+n);
			DROPDOWN_SetSel(hItem, sys_set_data.timing[n].start_hour);
		}
		for(n =0;n<8; n++){
			hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_16+n);
			DROPDOWN_SetSel(hItem, sys_set_data.timing[n].end_hour);
			
		}
		for(n =0;n<8; n++){
			hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_24+n);
			DROPDOWN_SetSel(hItem, sys_set_data.timing[n].start_min);			
		}
		for(n =0;n<8; n++){
			hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_32+n);
			DROPDOWN_SetSel(hItem, sys_set_data.timing[n].end_min);			
		}
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_40);
		DROPDOWN_SetSel(hItem, sys_set_data.fan_run_time);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_41);
		DROPDOWN_SetSel(hItem, sys_set_data.sample_interval);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_42);
		DROPDOWN_SetSel(hItem, sys_set_data.voice.value);
		
    // Initialization of 'save'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontHZ16);
    BUTTON_SetText(hItem, "保存");
    // Initialization of 'close'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontHZ16);
    BUTTON_SetText(hItem, "关闭");
		
		for(m=0;m<20;m++){
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
			TEXT_SetFont(hItem,&GUI_FontHZ16);
		}	
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, "湿    度");	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem, "温    度");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem, "二氧化碳");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetText(hItem, "氧    气");
		for(m=0;m<4;m++)
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4+m);
			TEXT_SetText(hItem, "风机联动值");
		}
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
		TEXT_SetText(hItem, "风机定时运行（时间段）");
		//？点？分---？点？分
		for(m=0;m<8;m++)
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9+m);
			TEXT_SetText(hItem, "点        分---       点       分");
		}
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
		TEXT_SetText(hItem, "风机运行时间：       分钟");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
		TEXT_SetText(hItem, "采样间隔       分钟");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
		TEXT_SetText(hItem, "音量");
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	hItem = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Sys_Set'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_32_ASCII);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'fan_gang4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "fan_gang1");
    //
    // Initialization of 'fan_gang3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
    CHECKBOX_SetText(hItem, "fan_gang2");
    //
    // Initialization of 'fan_gang2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
    CHECKBOX_SetText(hItem, "fan_gang3");
    //
    // Initialization of 'fan_gang1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
    CHECKBOX_SetText(hItem, "fan_gan4");
    //
    // Initialization of 'fan_gang_value1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'fan_gang_value2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'fan_gang_value3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_2);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'fan_gang_value4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_3);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'o2_alarm_value'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_4);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'co2_alarm_value'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_5);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'temperature_alarm_value'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_6);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'humidity_alarm_value'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_7);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing1_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_8);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing2_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_9);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing3_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_10);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing4_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_11);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing5_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_12);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing6_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_13);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing7_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_14);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing8_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_15);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing1_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_16);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing2_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_17);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing3_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_18);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing4_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_19);
    DROPDOWN_SetListHeight(hItem, 100);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    //
    // Initialization of 'timing5_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_20);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing6_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_21);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing7_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_22);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing8_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_23);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing1_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_24);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing2_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_25);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing3_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_26);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing4_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_27);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing5_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_28);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing6_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_29);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing7_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_30);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing8_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_31);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing1_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_32);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing2_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_33);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing3_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_34);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing4_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_35);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing5_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_36);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing6_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_37);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing7_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_38);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'timing8_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_39);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'fan_run_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_40);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of ' sample_interval'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_41);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'voice'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_42);
    DROPDOWN_SetFont(hItem, GUI_FONT_20_ASCII);
    DROPDOWN_SetListHeight(hItem, 100);
    //
    // Initialization of 'alarm_sounds'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);
    CHECKBOX_SetText(hItem, "alarm sounds");
    //
    // Initialization of 'voice'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
    CHECKBOX_SetText(hItem, "voice");
    //
    // Initialization of 'save'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'close'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)
		init(pMsg);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_CHECKBOX_0: // Notifications sent by 'fan_gang4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
				sys_set_data.fan_gang[0].enable = CHECKBOX_GetState(hItem);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_1: // Notifications sent by 'fan_gang3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
				sys_set_data.fan_gang[1].enable = CHECKBOX_GetState(hItem);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_2: // Notifications sent by 'fan_gang2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
				sys_set_data.fan_gang[2].enable = CHECKBOX_GetState(hItem);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_3: // Notifications sent by 'fan_gang1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
				sys_set_data.fan_gang[3].enable = CHECKBOX_GetState(hItem);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'fan_gang_value1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.fan_gang[0].Value = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_1: // Notifications sent by 'fan_gang_value2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.fan_gang[1].Value = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_2: // Notifications sent by 'fan_gang_value3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.fan_gang[2].Value = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_3: // Notifications sent by 'fan_gang_value4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.fan_gang[3].Value = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_4: // Notifications sent by 'o2_alarm_value'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.alarm.O2 = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_5: // Notifications sent by 'co2_alarm_value'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.alarm.CO2 = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_6: // Notifications sent by 'temperature_alarm_value'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.alarm.Temperature = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_7: // Notifications sent by 'humidity_alarm_value'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.alarm.Humidity = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_8: // Notifications sent by 'timing1_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[0].start_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_9: // Notifications sent by 'timing2_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[1].start_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_10: // Notifications sent by 'timing3_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[2].start_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_11: // Notifications sent by 'timing4_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[3].start_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));			
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_12: // Notifications sent by 'timing5_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[4].start_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_13: // Notifications sent by 'timing6_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[5].start_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_14: // Notifications sent by 'timing7_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[6].start_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_15: // Notifications sent by 'timing8_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[7].start_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_16: // Notifications sent by 'timing1_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[0].end_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_17: // Notifications sent by 'timing2_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[1].end_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_18: // Notifications sent by 'timing3_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[2].end_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_19: // Notifications sent by 'timing4_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[3].end_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_20: // Notifications sent by 'timing5_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[4].end_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_21: // Notifications sent by 'timing6_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[5].end_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_22: // Notifications sent by 'timing7_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[6].end_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_23: // Notifications sent by 'timing8_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[7].end_hour = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_24: // Notifications sent by 'timing1_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[0].start_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_25: // Notifications sent by 'timing2_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[1].start_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_26: // Notifications sent by 'timing3_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[2].start_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_27: // Notifications sent by 'timing4_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[3].start_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_28: // Notifications sent by 'timing5_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[4].start_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_29: // Notifications sent by 'timing6_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[5].start_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_30: // Notifications sent by 'timing7_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[6].start_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_31: // Notifications sent by 'timing8_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[7].start_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_32: // Notifications sent by 'timing1_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[0].end_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_33: // Notifications sent by 'timing2_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[1].end_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_34: // Notifications sent by 'timing3_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[2].end_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_35: // Notifications sent by 'timing4_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[3].end_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_36: // Notifications sent by 'timing5_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[4].end_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_37: // Notifications sent by 'timing6_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[5].end_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_38: // Notifications sent by 'timing7_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[6].end_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_39: // Notifications sent by 'timing8_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.timing[7].end_min = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_40: // Notifications sent by 'fan_run_time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.fan_run_time = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_41: // Notifications sent by ' sample_interval'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.sample_interval = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_42: // Notifications sent by 'voice'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				sys_set_data.voice.value = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, Id));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_4: // Notifications sent by 'alarm_sounds'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);
				sys_set_data.alarm.enable = CHECKBOX_GetState(hItem);
			
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_5: // Notifications sent by 'voice'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
				sys_set_data.voice.enable = CHECKBOX_GetState(hItem);
						
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'save'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)		
				save_sys_ini(&file_sys);			
				//write_sys_set_file();
			/*
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
				Test_ini(hItem);
				TEXT_SetText(hItem, IPADDR);//					
				GUI_Delay(2000);
				sprintf(IPADDR,"port=%d",PORT);
				TEXT_SetText(hItem, IPADDR);//					
				GUI_Delay(2000);	
				sprintf(IPADDR,"double=%f",double_test);
				TEXT_SetText(hItem, IPADDR);//*/
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'close'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(hItem, 0 );
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSys_Set
*/
WM_HWIN CreateSys_Set(void);
WM_HWIN CreateSys_Set(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
