/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "EmWinHZFont.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0       (GUI_ID_USER + 0x00)
#define ID_TEXT_0       (GUI_ID_USER + 0x01)
#define ID_TEXT_1       (GUI_ID_USER + 0x02)
#define ID_TEXT_2       (GUI_ID_USER + 0x03)
#define ID_TEXT_3       (GUI_ID_USER + 0x04)
#define ID_CHECKBOX_0       (GUI_ID_USER + 0x05)
#define ID_CHECKBOX_1       (GUI_ID_USER + 0x06)
#define ID_CHECKBOX_2       (GUI_ID_USER + 0x07)
#define ID_CHECKBOX_3       (GUI_ID_USER + 0x08)
#define ID_TEXT_4       (GUI_ID_USER + 0x09)
#define ID_TEXT_5       (GUI_ID_USER + 0x0A)
#define ID_TEXT_6       (GUI_ID_USER + 0x0B)
#define ID_TEXT_7       (GUI_ID_USER + 0x0C)
#define ID_DROPDOWN_0       (GUI_ID_USER + 0x0D)
#define ID_DROPDOWN_1       (GUI_ID_USER + 0x0E)
#define ID_DROPDOWN_2       (GUI_ID_USER + 0x0F)
#define ID_DROPDOWN_3       (GUI_ID_USER + 0x10)
#define ID_DROPDOWN_4       (GUI_ID_USER + 0x11)
#define ID_DROPDOWN_5       (GUI_ID_USER + 0x12)
#define ID_DROPDOWN_6       (GUI_ID_USER + 0x13)
#define ID_DROPDOWN_7       (GUI_ID_USER + 0x14)
#define ID_DROPDOWN_8       (GUI_ID_USER + 0x15)
#define ID_DROPDOWN_9       (GUI_ID_USER + 0x16)
#define ID_DROPDOWN_10       (GUI_ID_USER + 0x17)
#define ID_DROPDOWN_11       (GUI_ID_USER + 0x18)
#define ID_DROPDOWN_12       (GUI_ID_USER + 0x19)
#define ID_DROPDOWN_13       (GUI_ID_USER + 0x1A)
#define ID_DROPDOWN_14       (GUI_ID_USER + 0x1B)
#define ID_DROPDOWN_15       (GUI_ID_USER + 0x1C)
#define ID_DROPDOWN_16       (GUI_ID_USER + 0x1D)
#define ID_DROPDOWN_17       (GUI_ID_USER + 0x1E)
#define ID_DROPDOWN_18       (GUI_ID_USER + 0x1F)
#define ID_DROPDOWN_19       (GUI_ID_USER + 0x20)
#define ID_DROPDOWN_20       (GUI_ID_USER + 0x21)
#define ID_DROPDOWN_21       (GUI_ID_USER + 0x22)
#define ID_DROPDOWN_22       (GUI_ID_USER + 0x23)
#define ID_DROPDOWN_23       (GUI_ID_USER + 0x24)
#define ID_TEXT_8       (GUI_ID_USER + 0x25)
#define ID_TEXT_9       (GUI_ID_USER + 0x26)
#define ID_TEXT_10       (GUI_ID_USER + 0x27)
#define ID_TEXT_11       (GUI_ID_USER + 0x28)
#define ID_TEXT_12       (GUI_ID_USER + 0x29)
#define ID_TEXT_13       (GUI_ID_USER + 0x2A)
#define ID_TEXT_14       (GUI_ID_USER + 0x2B)
#define ID_TEXT_15       (GUI_ID_USER + 0x2C)
#define ID_TEXT_16       (GUI_ID_USER + 0x2D)
#define ID_TEXT_17       (GUI_ID_USER + 0x2E)
#define ID_CHECKBOX_4       (GUI_ID_USER + 0x2F)
#define ID_TEXT_18       (GUI_ID_USER + 0x30)
#define ID_DROPDOWN_24       (GUI_ID_USER + 0x31)
#define ID_DROPDOWN_25       (GUI_ID_USER + 0x32)
#define ID_TEXT_19       (GUI_ID_USER + 0x33)
#define ID_DROPDOWN_26       (GUI_ID_USER + 0x34)
#define ID_CHECKBOX_5       (GUI_ID_USER + 0x35)
#define ID_BUTTON_0       (GUI_ID_USER + 0x36)
#define ID_BUTTON_1       (GUI_ID_USER + 0x37)
#define ID_DROPDOWN_27       (GUI_ID_USER + 0x38)
#define ID_DROPDOWN_28       (GUI_ID_USER + 0x39)
#define ID_DROPDOWN_29       (GUI_ID_USER + 0x3A)
#define ID_DROPDOWN_30       (GUI_ID_USER + 0x3B)
#define ID_DROPDOWN_31       (GUI_ID_USER + 0x3C)
#define ID_DROPDOWN_32       (GUI_ID_USER + 0x3D)
#define ID_DROPDOWN_33       (GUI_ID_USER + 0x3E)
#define ID_DROPDOWN_34       (GUI_ID_USER + 0x3F)
#define ID_DROPDOWN_35       (GUI_ID_USER + 0x40)
#define ID_DROPDOWN_36       (GUI_ID_USER + 0x41)
#define ID_DROPDOWN_37       (GUI_ID_USER + 0x42)
#define ID_DROPDOWN_38       (GUI_ID_USER + 0x43)
#define ID_DROPDOWN_39       (GUI_ID_USER + 0x44)
#define ID_DROPDOWN_40       (GUI_ID_USER + 0x45)
#define ID_DROPDOWN_41       (GUI_ID_USER + 0x46)
#define ID_DROPDOWN_42       (GUI_ID_USER + 0x47)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
typedef struct{
	U8	start_hour;
	U8	start_min;
	U8	end_hour;
	U8	end_min;
}TIMING_TIME;
typedef	struct{
	float	alarm_O2;
	float	alarm_CO2;
	float alarm_temperature;
	float	alarm_humidity;
	_Bool	Fan_gang1;
	_Bool	fan_gang2;
	_Bool	Fan_gang3;
	_Bool	fan_gang4;
	float	fan_gang_value1;
	float	fan_gang_value2;
	float	fan_gang_value3;
	float	fan_gang_value4;
	TIMING_TIME	time1;
	TIMING_TIME	time2;
	TIMING_TIME	time3;
	TIMING_TIME	time4;
}SYS_SET;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Sys_Set", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "humidity", ID_TEXT_0, 95, 111, 131, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "temperature", ID_TEXT_1, 95, 81, 131, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CO2", ID_TEXT_2, 94, 48, 133, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "O2", ID_TEXT_3, 94, 21, 125, 22, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "fan_gang4", ID_CHECKBOX_0, 382, 110, 103, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "fan_gang3", ID_CHECKBOX_1, 383, 81, 106, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "fan_gang2", ID_CHECKBOX_2, 384, 52, 111, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "fan_gang1", ID_CHECKBOX_3, 383, 22, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_gang_value4", ID_TEXT_4, 495, 112, 96, 28, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_gang_value3", ID_TEXT_5, 494, 84, 93, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_gang_value2", ID_TEXT_6, 494, 52, 90, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_gang_value1", ID_TEXT_7, 494, 23, 84, 24, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "fan_gang_value3", ID_DROPDOWN_0, 602, 80, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "fan_gang_value2", ID_DROPDOWN_1, 601, 50, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "fan_gang_value1", ID_DROPDOWN_2, 602, 22, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "humidity_alarm_value", ID_DROPDOWN_3, 232, 113, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "temperature_alarm_value", ID_DROPDOWN_4, 231, 84, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "co2_alarm_value", ID_DROPDOWN_5, 230, 52, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "o2_alarm_value", ID_DROPDOWN_6, 229, 23, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "fan_gang_value4", ID_DROPDOWN_7, 602, 112, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing7_min_s", ID_DROPDOWN_8, 501, 226, 40, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing6_min_s", ID_DROPDOWN_9, 501, 198, 43, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing5_min_s", ID_DROPDOWN_10, 502, 169, 39, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing8_hour_s", ID_DROPDOWN_11, 418, 255, 50, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing7_hour_s", ID_DROPDOWN_12, 417, 225, 47, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing6_hour_s", ID_DROPDOWN_13, 417, 198, 47, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing5_hour_s", ID_DROPDOWN_14, 416, 168, 49, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing4_min_s", ID_DROPDOWN_15, 94, 258, 53, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing3_min_s", ID_DROPDOWN_16, 96, 230, 50, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing2_min_s", ID_DROPDOWN_17, 97, 198, 48, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing1_min_s", ID_DROPDOWN_18, 96, 167, 49, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing1_hour_s", ID_DROPDOWN_19, 28, 167, 42, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing4_hour_s", ID_DROPDOWN_20, 26, 257, 45, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing3_hour_s", ID_DROPDOWN_21, 27, 229, 43, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing2_hour_s", ID_DROPDOWN_22, 28, 198, 42, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing8_min_s", ID_DROPDOWN_23, 501, 254, 40, 18, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_timing_times", ID_TEXT_8, 41, 138, 257, 21, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_9, 475, 253, 257, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_10, 473, 224, 278, 23, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_11, 472, 195, 285, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_12, 473, 166, 272, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_13, 75, 195, 271, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_14, 76, 225, 262, 27, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_15, 76, 257, 268, 28, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dian feng dian feng", ID_TEXT_16, 73, 167, 277, 23, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_run_time", ID_TEXT_17, 16, 315, 212, 26, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "alarm_sounds", ID_CHECKBOX_4, 298, 310, 114, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, " sample interval_time", ID_TEXT_18, 498, 309, 170, 28, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_24, 125, 314, 47, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, " sample_interval", ID_DROPDOWN_25, 570, 309, 46, 18, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "volume", ID_TEXT_19, 26, 364, 80, 24, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_26, 88, 361, 80, 18, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "voice", ID_CHECKBOX_5, 212, 352, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "save", ID_BUTTON_0, 277, 384, 94, 33, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "close", ID_BUTTON_1, 437, 384, 86, 31, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing8_hour_end", ID_DROPDOWN_27, 596, 253, 43, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing7_hour_end", ID_DROPDOWN_28, 596, 225, 42, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing6_hour_end", ID_DROPDOWN_29, 594, 197, 43, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing5_hour_end", ID_DROPDOWN_30, 594, 167, 41, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing4_min_end", ID_DROPDOWN_31, 265, 259, 44, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing4_hour_end", ID_DROPDOWN_32, 196, 258, 43, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing3_min_end", ID_DROPDOWN_33, 266, 229, 42, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing3_hour_end", ID_DROPDOWN_34, 195, 227, 45, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing2_min_end", ID_DROPDOWN_35, 266, 196, 43, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing2_hour_end", ID_DROPDOWN_36, 196, 197, 42, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing1_min_end", ID_DROPDOWN_37, 266, 168, 44, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing1_hour_end", ID_DROPDOWN_38, 193, 167, 45, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing6_min_end", ID_DROPDOWN_39, 665, 197, 46, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing5_min_end", ID_DROPDOWN_40, 666, 167, 44, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing8_min_end", ID_DROPDOWN_41, 667, 252, 47, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "timing7_min_end", ID_DROPDOWN_42, 666, 225, 46, 18, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void init(WM_MESSAGE * pMsg){
	WM_HWIN hItem;
  int     NCode;
  int     Id;
	//初始化FRAMEWIN
	hItem = pMsg->hWin;
	//FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	//FRAMEWIN_SetTitleHeight(hItem, 10);
	FRAMEWIN_SetFont(hItem,&GUI_FontHZ32);
	//FRAMEWIN_SetTextColor(hItem, GUI_RED);
	FRAMEWIN_SetText(hItem, "系统设置");
	//
    // Initialization of 'fan_gang4'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetFont(hItem,&GUI_FontHZ16);
    CHECKBOX_SetText(hItem, "风机联动");
    // Initialization of 'fan_gang3'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
		CHECKBOX_SetFont(hItem,&GUI_FontHZ16);
    CHECKBOX_SetText(hItem, "风机联动");
    // Initialization of 'fan_gang2'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
		CHECKBOX_SetFont(hItem,&GUI_FontHZ16);
    CHECKBOX_SetText(hItem, "风机联动");
    // Initialization of 'fan_gang1'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
		CHECKBOX_SetFont(hItem,&GUI_FontHZ16);
    CHECKBOX_SetText(hItem, "风机联动");
    // Initialization of 'alarm_sounds'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);		
		CHECKBOX_SetFont(hItem,&GUI_FontHZ16);
    CHECKBOX_SetText(hItem, "报警器报警");
    // Initialization of 'voice'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
		CHECKBOX_SetFont(hItem,&GUI_FontHZ16);
    CHECKBOX_SetText(hItem, "语音");
    // Initialization of 'save'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontHZ16);
    BUTTON_SetText(hItem, "保存");
    // Initialization of 'close'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontHZ16);
    BUTTON_SetText(hItem, "关闭");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "湿    度");	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "温    度");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "二氧化碳");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "氧    气");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "风机联动值");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "风机联动值");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "风机联动值");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "风机联动值");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "风机定时运行（时间段）");
		//？点？分---？点？分
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
		TEXT_SetText(hItem, "点       分---       点       分");	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
		TEXT_SetText(hItem, "点       分---       点       分");	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
		TEXT_SetText(hItem, "点       分---       点       分");	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
		TEXT_SetText(hItem, "点       分---       点       分");	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
		TEXT_SetText(hItem, "点       分---       点       分");	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
		TEXT_SetText(hItem, "点       分---       点       分");	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
		TEXT_SetText(hItem, "点       分---       点       分");	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
		TEXT_SetText(hItem, "点       分---       点       分");	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "风机运行时间：       分钟");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "采样间隔       分钟");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
		TEXT_SetFont(hItem,&GUI_FontHZ16);		
		TEXT_SetText(hItem, "音量");
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	hItem = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Sys_Set'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_32_ASCII);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'fan_gang4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "fan_gan4");
    //
    // Initialization of 'fan_gang3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
    CHECKBOX_SetText(hItem, "fan_gang3");
    //
    // Initialization of 'fan_gang2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
    CHECKBOX_SetText(hItem, "fan_gang2");
    //
    // Initialization of 'fan_gang1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
    CHECKBOX_SetText(hItem, "fan_gang1");
    //
    // Initialization of 'fan_gang_value3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'fan_gang_value2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'fan_gang_value1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_2);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'humidity_alarm_value'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_3);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'temperature_alarm_value'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_4);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'co2_alarm_value'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_5);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'o2_alarm_value'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_6);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'fan_gang_value4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_7);
    DROPDOWN_AddString(hItem, "12");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing7_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_8);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing6_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_9);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing5_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_10);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing8_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_11);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing7_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_12);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing6_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_13);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing5_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_14);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing4_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_15);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing3_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_16);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing2_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_17);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing1_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_18);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing1_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_19);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing4_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_20);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing3_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_21);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing2_hour_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_22);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing8_min_s'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_23);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'alarm_sounds'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);
    CHECKBOX_SetText(hItem, "alarm sounds");
    //
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_24);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of ' sample_interval'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_25);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_26);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'voice'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
    CHECKBOX_SetText(hItem, "voice");
    //
    // Initialization of 'save'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'close'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'timing8_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_27);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing7_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_28);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing6_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_29);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing5_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_30);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing4_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_31);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing4_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_32);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing3_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_33);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing3_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_34);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing2_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_35);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing2_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_36);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing1_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_37);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing1_hour_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_38);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing6_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_39);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing5_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_40);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing8_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_41);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    //
    // Initialization of 'timing7_min_end'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_42);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    // USER START (Optionally insert additional code for further widget initialization)
		init(pMsg);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_CHECKBOX_0: // Notifications sent by 'fan_gang4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_1: // Notifications sent by 'fan_gang3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_2: // Notifications sent by 'fan_gang2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_3: // Notifications sent by 'fan_gang1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'fan_gang_value3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_1: // Notifications sent by 'fan_gang_value2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_2: // Notifications sent by 'fan_gang_value1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_3: // Notifications sent by 'humidity_alarm_value'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_4: // Notifications sent by 'temperature_alarm_value'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_5: // Notifications sent by 'co2_alarm_value'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_6: // Notifications sent by 'o2_alarm_value'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_7: // Notifications sent by 'fan_gang_value4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_8: // Notifications sent by 'timing7_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_9: // Notifications sent by 'timing6_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_10: // Notifications sent by 'timing5_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_11: // Notifications sent by 'timing8_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_12: // Notifications sent by 'timing7_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_13: // Notifications sent by 'timing6_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_14: // Notifications sent by 'timing5_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_15: // Notifications sent by 'timing4_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_16: // Notifications sent by 'timing3_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_17: // Notifications sent by 'timing2_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_18: // Notifications sent by 'timing1_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_19: // Notifications sent by 'timing1_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_20: // Notifications sent by 'timing4_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_21: // Notifications sent by 'timing3_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_22: // Notifications sent by 'timing2_hour_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_23: // Notifications sent by 'timing8_min_s'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_4: // Notifications sent by 'alarm_sounds'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_24: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_25: // Notifications sent by ' sample_interval'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_26: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_5: // Notifications sent by 'voice'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'save'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'close'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(hItem, 0 );
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_27: // Notifications sent by 'timing8_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_28: // Notifications sent by 'timing7_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_29: // Notifications sent by 'timing6_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_30: // Notifications sent by 'timing5_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_31: // Notifications sent by 'timing4_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_32: // Notifications sent by 'timing4_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_33: // Notifications sent by 'timing3_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_34: // Notifications sent by 'timing3_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_35: // Notifications sent by 'timing2_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_36: // Notifications sent by 'timing2_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_37: // Notifications sent by 'timing1_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_38: // Notifications sent by 'timing1_hour_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_39: // Notifications sent by 'timing6_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_40: // Notifications sent by 'timing5_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_41: // Notifications sent by 'timing8_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_42: // Notifications sent by 'timing7_min_end'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSys_Set
*/
WM_HWIN CreateSys_Set(void);
WM_HWIN CreateSys_Set(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
